namespace TownOfUs.Modules.Localization;

public enum TouNames
{
    FoolsMode,
    TertiaryAbility,
    ModifierAbility,

    // Client Options
    ClientOptionsButton,
    DeadSeeGhosts,
    ShowVents,
    ShowWelcomeMessage,
    ShowSummaryMessage,
    ColorPlayerName,
    UseCrewmateTeamColor,
    ShowShieldHud,
    ButtonUIFactor,
    OffsetButtons,
    SortGuessingByAlignment,
    PreciseCooldowns,
    ArrowStyle,
    ArrowDefault,
    ArrowDarkGlow,
    ArrowColorGlow,
    ArrowLegacy,

    // Player Colors
    Watermelon,
    Chocolate,
    SkyBlue,
    Beige,
    Magenta,
    SeaGreen,
    Lilac,
    Olive,
    Azure,
    Plum,
    Jungle,
    Mint,
    Chartreuse,
    Macau,
    Tawny,
    Gold,
    Snow,
    Turquoise,
    Nacho,
    Blood,
    Grass,
    Mandarin,
    Glass,
    Ash,
    Midnight,
    Steel,
    Silver,
    Shimmer,
    Crimson,
    Charcoal,
    Violet,
    Denim,
    CottonCandy,
    Rainbow,

    // Role Alignments
    CrewmateInvestigative,
    CrewmateKilling,
    CrewmatePower,
    CrewmateProtective,
    CrewmateSupport,
    NeutralBenign,
    NeutralEvil,
    NeutralOutlier,
    NeutralKilling,
    ImpostorConcealing,
    ImpostorKilling,
    ImpostorPower,
    ImpostorSupport,

    // Role Buckets
    CommonCrew,
    SpecialCrew,
    RandomCrew,
    CommonNeutral,
    RandomNeutral,
    NonImp,
    CommonImp,
    SpecialImp,
    RandomImp,
    Any,
    CrewInvestigative,
    CrewKilling,
    CrewPower,
    CrewProtective,
    CrewSupport,
    ImpConcealing,
    ImpKilling,
    ImpPower,
    ImpSupport,

    // Highlighted Keywords (like Non Imp showing Imp as red)
    CrewmateKeyword,
    CrewKeyword,
    NeutralKeyword,
    NeutKeyword,
    ImpostorKeyword,
    ImpKeyword,

    // Modifier Types
    Alliance,
    Universal,
    CrewmateAlliance,
    CrewmateUtility,
    CrewmateVisibility,
    CrewmatePostmortem,
    CrewmatePassive,
    NeutralAlliance,
    NeutralUtility,
    NeutralVisibility,
    NeutralPostmortem,
    NeutralPassive,
    ImpostorAlliance,
    ImpostorUtility,
    ImpostorVisibility,
    ImpostorPostmortem,
    ImpostorPassive,
    UniversalUtility,
    UniversalVisibility,
    UniversalPostmortem,
    UniversalPassive,
    AssailantUtility,
    AssailantVisibility,
    AssailantPostmortem,
    AssailantPassive,
    NonCrewmate,
    NonCrewUtility,
    NonCrewVisibility,
    NonCrewPostmortem,
    NonCrewPassive,
    NonNeutral,
    NonNeutUtility,
    NonNeutVisibility,
    NonNeutPostmortem,
    NonNeutPassive,
    NonImpostor,
    NonImpUtility,
    NonImpVisibility,
    NonImpPostmortem,
    NonImpPassive,
    External,
    Other,

    // Other keywords, used by options and the wiki
    Roles,
    Modifiers,
    Amount,
    Chance,

    // Crewmate Roles
    Altruist,
    Aurial,
    Cleric,
    Deputy,
    Detective,
    Engineer,
    Haunter,
    Hunter,
    Imitator,
    Investigator,
    Jailor,
    Lookout,
    Mayor,
    Medic,
    Medium,
    Mirrorcaster,
    Mystic,
    Oracle,
    Plumber,
    Politician,
    Prosecutor,
    Seer,
    Sheriff,
    Snitch,
    Spy,
    Swapper,
    Tracker,
    Transporter,
    Trapper,
    Veteran,
    Vigilante,
    Warden,

    // Impostor Roles
    Ambassador,
    Ambusher,
    Blackmailer,
    Bomber,
    Eclipsal,
    Escapist,
    Grenadier,
    Herbalist,
    Hypnotist,
    Infestor,
    Janitor,
    Miner,
    Morphling,
    Scavenger,
    Swooper,
    Traitor,
    Undertaker,
    Venerer,
    Warlock,

    // Neutral Roles
    Amnesiac,
    Arsonist,
    Doomsayer,
    Executioner,
    Glitch,
    GuardianAngel,
    Inquisitor,
    Jester,
    Juggernaut,
    Mercenary,
    Pestilence,
    Phantom,
    Plaguebearer,
    SoulCollector,
    Survivor,
    Vampire,
    Werewolf,

    // Alliance Modifiers
    Egotist,
    Lover,
    Lovers, // for plural

    // Universal Modifiers
    ButtonBarry,
    Flash,
    Giant,
    Immovable,
    Mini,
    Radar,
    Satellite,
    Shy,
    SixthSense,
    Sleuth,
    Tiebreaker,

    // Impostor Modifiers
    Disperser,
    Saboteur,
    Telepath,
    Underdog,

    // Assailant Modifiers (NK/Imp)
    Assassin,
    DoubleShot,

    // Crewmate Modifiers
    Aftermath,
    Bait,
    Celebrity,
    Diseased,
    Frosty,
    Multitasker,
    Noisemaker,
    Operative,
    Rotting,
    Scientist,
    Scout,
    Taskmaster,
    Torch,

    // Other Modifiers
    FirstDeathShield,
    Scatter,

    // EVERYTHING BELOW HERE IS FOR THE SIDEMEN, THEY ARE NOT FOR PUBLIC RELEASE!
    Astral,
    PuppetMaster,
    Mage,
    Sandworm,
    Rcxd,
    Poisoner,
    Sniper,
    Cannibal,
    Timelord
}